# Generated by Django 4.1.7 on 2023-04-16 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueWedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('groom_fname', models.CharField(default='', max_length=16)),
                ('groom_lname', models.CharField(default='', max_length=16)),
                ('bride_fname', models.CharField(default='', max_length=16)),
                ('bried_lname', models.CharField(default='', max_length=16)),
                ('wedding_date', models.DateField()),
                ('response_date', models.DateField()),
                ('groom_gathering', models.CharField(blank=True, default='', max_length=64)),
                ('groom_gathering_time', models.TimeField(blank=True)),
                ('bride_gathering', models.CharField(blank=True, default='', max_length=64)),
                ('bride_gathering_time', models.TimeField(blank=True)),
                ('church_name', models.CharField(default='', max_length=48)),
                ('church_time', models.TimeField()),
                ('restaurant_name', models.CharField(default='', max_length=48)),
                ('restaurant_time', models.TimeField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_fname', models.CharField(default='', max_length=16)),
                ('guest_lname', models.CharField(default='', max_length=16)),
                ('plusone_fname', models.CharField(blank=True, default='', max_length=16)),
                ('plusone_lname', models.CharField(blank=True, default='', max_length=16)),
                ('guest_type', models.CharField(choices=[('SOLO', 'Solo'), ('PAR', 'Par'), ('OBITELJ', 'Obitelj')], default='', max_length=7)),
                ('couple', models.BooleanField(default=False)),
                ('plusone', models.BooleanField(default=False)),
                ('coming', models.BooleanField(default=False)),
                ('kids', models.SmallIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=256)),
                ('wedding_owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wedding', to='groomie.uniquewedding')),
            ],
        ),
        migrations.CreateModel(
            name='BasicWedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('groom_fname', models.CharField(default='', max_length=16)),
                ('groom_lname', models.CharField(default='', max_length=16)),
                ('bride_fname', models.CharField(default='', max_length=16)),
                ('bried_lname', models.CharField(default='', max_length=16)),
                ('wedding_date', models.DateField()),
                ('response_date', models.DateField()),
                ('groom_gathering', models.CharField(blank=True, default='', max_length=64)),
                ('groom_gathering_time', models.TimeField(blank=True)),
                ('bride_gathering', models.CharField(blank=True, default='', max_length=64)),
                ('bride_gathering_time', models.TimeField(blank=True)),
                ('church_name', models.CharField(default='', max_length=48)),
                ('church_time', models.TimeField()),
                ('restaurant_name', models.CharField(default='', max_length=48)),
                ('restaurant_time', models.TimeField()),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basicwedding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasicGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_fname', models.CharField(default='', max_length=16)),
                ('guest_lname', models.CharField(default='', max_length=16)),
                ('plusone_fname', models.CharField(blank=True, default='', max_length=16)),
                ('plusone_lname', models.CharField(blank=True, default='', max_length=16)),
                ('with_kids', models.BooleanField(default=False)),
                ('plusone', models.BooleanField(default=False)),
                ('coming', models.BooleanField(default=False)),
                ('kids', models.SmallIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=256)),
                ('wedding_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wedding', to='groomie.basicwedding')),
            ],
        ),
    ]
