# Generated by Django 4.1.7 on 2023-06-19 21:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=32, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=32, verbose_name='Prezime')),
                ('broj_telefona', models.IntegerField(null=True, verbose_name='Broj telefona')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=5)),
                ('mobile_number', models.CharField(max_length=14)),
                ('wedding', models.CharField(max_length=13)),
                ('price', models.FloatField(default=1)),
                ('total_cost', models.FloatField(default=1)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirm', 'Confirm')], default='pending', max_length=20)),
                ('event_type', models.CharField(choices=[('basic', 'Basic'), ('nique', 'Unique')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirm', 'Confirm')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('cutomer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
