# Generated by Django 4.1.7 on 2023-04-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='broj_telefona',
            field=models.IntegerField(null=True, verbose_name='Broj telefona'),
        ),
    ]
